import { db } from "@/lib/db";
import { audit } from "./audit";
import { dispatchWebhooks, type WebhookEvent } from "./webhooks";
import { evaluateEscalation } from "./escalation";

/* ============================================================
   NEXURA OS — automation engine
   Rules are visible/editable in the Automation Builder UI.
   Execution is deterministic server-side code (never AI) —
   the engine coordinates, humans approve high-risk steps.
   Every run is recorded in NxWorkflowRun + audit trail.
   ============================================================ */

export type NxTrigger =
  "result.critical" | "discharge.confirmed" | "bed.ready" | "order.created" | "appointment.created";

export interface AutomationCtx {
  hospitalId: string;
  actorName: string;
  actorRole: string;
  patientId?: string;
  patientName?: string;
  patientUhid?: string;
  relatedId?: string;
  detail?: Record<string, unknown>;
}

interface StepLog {
  name: string;
  status: "done" | "awaiting_approval" | "skipped";
  detail: string;
  at: string;
}

function nowISO() {
  return new Date().toISOString();
}

export async function createTask(input: {
  hospitalId: string;
  title: string;
  type?: string;
  priority?: string;
  ownerRole?: string;
  ownerName?: string;
  patientId?: string;
  patientName?: string;
  patientUhid?: string;
  location?: string;
  dueMinutes?: number;
  reason?: string;
  sourceModule?: string;
  relatedId?: string;
}) {
  const dueAt = input.dueMinutes ? new Date(Date.now() + input.dueMinutes * 60000) : null;
  return db.nxTask.create({
    data: {
      hospitalId: input.hospitalId,
      title: input.title,
      type: input.type || "task",
      priority: input.priority || "medium",
      ownerRole: input.ownerRole,
      ownerName: input.ownerName,
      patientId: input.patientId,
      patientName: input.patientName,
      patientUhid: input.patientUhid,
      location: input.location,
      dueAt,
      reason: input.reason,
      sourceModule: input.sourceModule || "automations",
      relatedId: input.relatedId,
    },
  });
}

async function postMessage(
  hospitalId: string,
  channelKey: string,
  senderName: string,
  senderRole: string,
  body: string,
  patientId?: string,
) {
  await db.nxMessage.create({
    data: { hospitalId, channelKey, senderName, senderRole, body, patientId },
  });
}

/* ---------- Trigger implementations ---------- */

async function runCriticalResult(ctx: AutomationCtx): Promise<StepLog[]> {
  const steps: StepLog[] = [];
  const testName = String(ctx.detail?.testName || "Laboratory result");
  await createTask({
    hospitalId: ctx.hospitalId,
    title: `CRITICAL result — ${testName} · ${ctx.patientName || ctx.patientUhid || "patient"}`,
    type: "result",
    priority: "critical",
    ownerRole: "doctor",
    patientId: ctx.patientId,
    patientName: ctx.patientName,
    patientUhid: ctx.patientUhid,
    dueMinutes: 15,
    reason: "Critical laboratory value — acknowledgement required within 15 min per safety policy",
    sourceModule: "labs",
    relatedId: ctx.relatedId,
  });
  steps.push({
    name: "Create critical acknowledgement task for attending doctor",
    status: "done",
    detail: "15-minute SLA",
    at: nowISO(),
  });

  await db.nxIncident.create({
    data: {
      hospitalId: ctx.hospitalId,
      severity: "critical",
      status: "open",
      category: "clinical",
      title: `Critical lab value: ${testName} — ${ctx.patientName || ctx.patientUhid || ""}`.trim(),
      description: `Auto-generated by Nexura automation on result validation. Result must be acknowledged by the responsible clinician.`,
      patientId: ctx.patientId,
      reportedBy: "Nexura Automation",
      location: String(ctx.detail?.location || ""),
    },
  });
  steps.push({
    name: "Open critical incident (Command Center visibility)",
    status: "done",
    detail: "Category: clinical",
    at: nowISO(),
  });

  await postMessage(
    ctx.hospitalId,
    `care-team:${ctx.relatedId || ctx.patientId || "general"}`,
    "Nexura Automation",
    "system",
    `CRITICAL result for ${ctx.patientName || ctx.patientUhid}: ${testName}. Attending doctor notified — escalation fires if unacknowledged in 15 min.`,
    ctx.patientId,
  );
  steps.push({
    name: "Notify care team channel",
    status: "done",
    detail: "Escalation armed at 15 min",
    at: nowISO(),
  });
  return steps;
}

async function runDischargeConfirmed(ctx: AutomationCtx): Promise<StepLog[]> {
  const steps: StepLog[] = [];
  const who = ctx.patientName || ctx.patientUhid || "patient";

  // 1. Bed lifecycle: occupied -> cleaning_required
  const admission = ctx.relatedId
    ? await db.hospitalAdmission.findUnique({
        where: { id: ctx.relatedId },
        include: { bed: true },
      })
    : null;
  if (admission?.bed) {
    await db.hospitalBed.update({
      where: { id: admission.bed.id },
      data: { status: "cleaning_required", currentPatientUhid: null },
    });
    steps.push({
      name: "Mark bed unavailable — cleaning required",
      status: "done",
      detail: `Bed ${admission.bed.bedNumber} → cleaning_required`,
      at: nowISO(),
    });
    await createTask({
      hospitalId: ctx.hospitalId,
      title: `Clean bed ${admission.bed.bedNumber} (${admission.bed.wardId ? "" : ""}post-discharge)`,
      type: "cleaning",
      priority: "high",
      ownerRole: "facilities",
      patientName: ctx.patientName,
      patientUhid: ctx.patientUhid,
      location: admission.bed.bedNumber,
      dueMinutes: 45,
      reason: "Bed turnaround SLA — target ready within 45 min of discharge",
      sourceModule: "automations",
      relatedId: admission.bed.id,
    });
    steps.push({
      name: "Create cleaning task for facilities team",
      status: "done",
      detail: "45-min SLA",
      at: nowISO(),
    });
  } else {
    steps.push({
      name: "Bed lifecycle",
      status: "skipped",
      detail: "No bed attached to admission",
      at: nowISO(),
    });
  }

  // 2. Pharmacy — discharge meds
  await createTask({
    hospitalId: ctx.hospitalId,
    title: `Prepare discharge medications — ${who}`,
    type: "task",
    priority: "high",
    ownerRole: "pharmacist",
    patientId: ctx.patientId,
    patientName: ctx.patientName,
    patientUhid: ctx.patientUhid,
    dueMinutes: 60,
    reason: "Discharge medication readiness prevents discharge delays",
    sourceModule: "automations",
  });
  steps.push({
    name: "Notify pharmacy to prepare discharge meds",
    status: "done",
    detail: "60-min SLA",
    at: nowISO(),
  });

  // 3. Billing — finalize invoice
  await createTask({
    hospitalId: ctx.hospitalId,
    title: `Finalize bill & claim documentation — ${who}`,
    type: "approval",
    priority: "medium",
    ownerRole: "admin",
    patientId: ctx.patientId,
    patientName: ctx.patientName,
    patientUhid: ctx.patientUhid,
    dueMinutes: 120,
    reason: "Revenue cycle: charges must be reconciled before claim submission",
    sourceModule: "automations",
  });
  steps.push({
    name: "Notify billing to finalize invoice",
    status: "done",
    detail: "Includes insurance claim docs",
    at: nowISO(),
  });

  // 4. Follow-up appointment + 48h check
  await createTask({
    hospitalId: ctx.hospitalId,
    title: `Schedule follow-up appointment — ${who}`,
    type: "followup",
    priority: "medium",
    ownerRole: "reception",
    patientId: ctx.patientId,
    patientName: ctx.patientName,
    patientUhid: ctx.patientUhid,
    dueMinutes: 240,
    reason: "Follow-up within 7 days reduces readmission risk",
    sourceModule: "automations",
  });
  steps.push({
    name: "Create follow-up scheduling task",
    status: "done",
    detail: "Target: within 7 days",
    at: nowISO(),
  });

  await createTask({
    hospitalId: ctx.hospitalId,
    title: `48-hour post-discharge check-in call — ${who}`,
    type: "followup",
    priority: "high",
    ownerRole: "nurse",
    patientId: ctx.patientId,
    patientName: ctx.patientName,
    patientUhid: ctx.patientUhid,
    dueMinutes: 48 * 60,
    reason: "Early post-discharge contact detects deterioration",
    sourceModule: "automations",
  });
  steps.push({
    name: "Create 48-hour follow-up task",
    status: "done",
    detail: "Escalates if incomplete",
    at: nowISO(),
  });

  // 5. Patient + caregiver message
  await postMessage(
    ctx.hospitalId,
    `patient:${ctx.patientId || "general"}`,
    "Nexura Automation",
    "system",
    `Discharge confirmed for ${who}. Care instructions and medications are in your portal. A follow-up will be scheduled within 7 days.`,
    ctx.patientId,
  );
  steps.push({
    name: "Notify patient & approved caregiver",
    status: "done",
    detail: "Portal message sent",
    at: nowISO(),
  });

  return steps;
}

async function runBedReady(ctx: AutomationCtx): Promise<StepLog[]> {
  const steps: StepLog[] = [];
  const bed = ctx.relatedId
    ? await db.hospitalBed.findUnique({ where: { id: ctx.relatedId } })
    : null;
  if (!bed)
    return [{ name: "Locate bed", status: "skipped", detail: "Bed not found", at: nowISO() }];
  await createTask({
    hospitalId: ctx.hospitalId,
    title: `Bed ${bed.bedNumber} ready — assign next patient`,
    type: "task",
    priority: "high",
    ownerRole: "command",
    location: bed.bedNumber,
    reason: "Ready bed with waiting list — minimize turnaround gap",
    sourceModule: "automations",
    relatedId: bed.id,
    dueMinutes: 30,
  });
  steps.push({
    name: "Notify bed management to assign next patient",
    status: "done",
    detail: `Bed ${bed.bedNumber} is ready`,
    at: nowISO(),
  });
  return steps;
}

async function runOrderCreated(ctx: AutomationCtx): Promise<StepLog[]> {
  const steps: StepLog[] = [];
  const orderType = String(ctx.detail?.orderType || "lab");
  const priority = String(ctx.detail?.priority || "routine");
  if (orderType === "lab") {
    await createTask({
      hospitalId: ctx.hospitalId,
      title: `Specimen collection — ${ctx.patientName || ctx.patientUhid || "patient"}${priority === "stat" ? " (STAT)" : ""}`,
      type: "order",
      priority: priority === "stat" ? "critical" : priority === "urgent" ? "high" : "medium",
      ownerRole: "lab",
      patientId: ctx.patientId,
      patientName: ctx.patientName,
      patientUhid: ctx.patientUhid,
      location: String(ctx.detail?.location || ""),
      dueMinutes: priority === "stat" ? 10 : priority === "urgent" ? 30 : 90,
      reason:
        priority === "stat"
          ? "STAT order — collection within 10 minutes"
          : "Standard specimen collection SLA",
      sourceModule: "lab",
      relatedId: ctx.relatedId,
    });
    steps.push({
      name: "Queue specimen collection",
      status: "done",
      detail: `Priority: ${priority}`,
      at: nowISO(),
    });
  }
  if (orderType === "medication") {
    await createTask({
      hospitalId: ctx.hospitalId,
      title: `Pharmacist verification — new medication order (${ctx.patientName || ctx.patientUhid || "patient"})`,
      type: "approval",
      priority: priority === "stat" ? "critical" : "high",
      ownerRole: "pharmacist",
      patientId: ctx.patientId,
      patientName: ctx.patientName,
      patientUhid: ctx.patientUhid,
      dueMinutes: priority === "stat" ? 10 : 30,
      reason: "Medication safety: pharmacist verification before dispensing",
      sourceModule: "pharmacy",
      relatedId: ctx.relatedId,
    });
    steps.push({
      name: "Queue pharmacist verification",
      status: "done",
      detail: "Interaction & dose check",
      at: nowISO(),
    });
  }
  if (orderType === "imaging") {
    await createTask({
      hospitalId: ctx.hospitalId,
      title: `Imaging worklist entry — ${ctx.patientName || ctx.patientUhid || "patient"}`,
      type: "order",
      priority: priority === "stat" ? "critical" : priority === "urgent" ? "high" : "medium",
      ownerRole: "nurse",
      patientId: ctx.patientId,
      patientName: ctx.patientName,
      patientUhid: ctx.patientUhid,
      dueMinutes: priority === "stat" ? 15 : 60,
      reason: "Patient preparation & transport for imaging",
      sourceModule: "orders",
      relatedId: ctx.relatedId,
    });
    steps.push({
      name: "Add to imaging worklist",
      status: "done",
      detail: "Prep + transport task created",
      at: nowISO(),
    });
  }
  return steps;
}

async function runAppointmentCreated(ctx: AutomationCtx): Promise<StepLog[]> {
  const steps: StepLog[] = [];
  const who = ctx.patientName || "Patient";
  await createTask({
    hospitalId: ctx.hospitalId,
    title: `Send appointment reminder — ${who}`,
    type: "task",
    priority: "low",
    ownerRole: "reception",
    patientId: ctx.patientId,
    patientName: ctx.patientName,
    dueMinutes: 60,
    reason: "Reminders reduce no-show rate",
    sourceModule: "automations",
    relatedId: ctx.relatedId,
  });
  steps.push({
    name: "Queue appointment reminder",
    status: "done",
    detail: "SMS + portal",
    at: nowISO(),
  });
  await createTask({
    hospitalId: ctx.hospitalId,
    title: `Pre-visit prep & digital forms — ${who}`,
    type: "task",
    priority: "low",
    ownerRole: "reception",
    patientId: ctx.patientId,
    patientName: ctx.patientName,
    dueMinutes: 120,
    reason: "Digital pre-registration shortens check-in",
    sourceModule: "automations",
    relatedId: ctx.relatedId,
  });
  steps.push({
    name: "Queue digital pre-registration",
    status: "done",
    detail: "Forms sent to patient portal",
    at: nowISO(),
  });
  return steps;
}

const RUNNERS: Record<NxTrigger, (ctx: AutomationCtx) => Promise<StepLog[]>> = {
  "result.critical": runCriticalResult,
  "discharge.confirmed": runDischargeConfirmed,
  "bed.ready": runBedReady,
  "order.created": runOrderCreated,
  "appointment.created": runAppointmentCreated,
};

/** Fire every enabled rule bound to this trigger. Never throws.
 *  Also fans out to (a) webhook subscribers and (b) escalation policies —
 *  integrations and safety nets ride the same deterministic trigger path. */
export async function fire(trigger: NxTrigger, ctx: AutomationCtx): Promise<void> {
  try {
    dispatchWebhooks(ctx.hospitalId, trigger as WebhookEvent, {
      patientId: ctx.patientId,
      patientUhid: ctx.patientUhid,
      patientName: ctx.patientName,
      relatedId: ctx.relatedId,
    });
    void evaluateEscalation(ctx.hospitalId, trigger as WebhookEvent, ctx.relatedId || "");
    const rules = await db.nxAutomationRule.findMany({
      where: { hospitalId: ctx.hospitalId, triggerType: trigger, enabled: true },
    });
    const runner = RUNNERS[trigger];
    for (const rule of rules) {
      const startedAt = new Date();
      let steps: StepLog[] = [];
      let status = "completed";
      try {
        steps = await runner(ctx);
      } catch (err) {
        status = "failed";
        steps = [{ name: "Execution", status: "skipped", detail: String(err), at: nowISO() }];
      }
      await db.nxWorkflowRun.create({
        data: {
          hospitalId: ctx.hospitalId,
          ruleId: rule.id,
          ruleName: rule.name,
          patientId: ctx.patientId,
          patientUhid: ctx.patientUhid,
          status,
          currentStep: steps[steps.length - 1]?.name,
          steps: JSON.stringify(steps),
          startedAt,
          completedAt: new Date(),
        },
      });
      await db.nxAutomationRule.update({
        where: { id: rule.id },
        data: { lastRunAt: new Date(), runCount: { increment: 1 } },
      });
      await audit({
        hospitalId: ctx.hospitalId,
        actorName: "Nexura Automation",
        actorRole: "system",
        action: `automation.${trigger}`,
        entityType: "automation_run",
        entityId: rule.id,
        patientId: ctx.patientId,
        detail: { rule: rule.name, status, steps: steps.length },
      });
    }
  } catch (err) {
    console.error(`[nx-automations] trigger ${trigger} failed`, err);
  }
}
