import {
  Compass, MonitorSmartphone, CalendarDays, Sparkles, HeartPulse,
  MessageCircle, Globe,
} from "lucide-react";
import type { HiwSection } from "./types";

/* Group accent palette mirrors the site: coral / honey / sage / blue */

export const SECTIONS_START_PATIENTS: HiwSection[] = [
  {
    id: "big-picture",
    group: "start",
    icon: Compass,
    accent: "#A16207",
    title: "The whole ecosystem",
    kicker: "Eight products, one spine. Every feature below runs on the same data, the same login and the same rules.",
    minutes: "2 min",
    steps: [
      { title: "Start on the homepage", desc: "Search anything with ⌘K, or press “Book a visit” for a four-step appointment flow that takes under a minute." },
      { title: "The booking lands in Hospital OS", desc: "Doctors and front desk see the new visit on their OPD queue the moment it is confirmed — no phone calls, no re-entry." },
      { title: "The clinician works inside one shell", desc: "EHR, labs, prescriptions, beds, billing and OT schedules all live in one desktop-style operating system." },
      { title: "AI joins quietly", desc: "Triage scoring, report reading and clinical drafts are produced by Gemini behind governance guardrails — humans always approve." },
      { title: "Everything flows back to you", desc: "Records appear in the Patient Portal, conversations continue in Nexura Connect, and daily health runs through Know Your Health's 15 AI tools." },
      { title: "The business side stays honest", desc: "Pharmacia bills it, insurance & TPA adjudicate it, and the Governance & Trust Center proves it all with hash-chained audits." },
    ],
    hood: ["8 products", "56 API route families", "132 DB models", "Realtime SSE", "6 languages"],
    cta: { kind: "booking", label: "Try it — book a visit" },
  },
  {
    id: "desktop",
    group: "start",
    icon: MonitorSmartphone,
    accent: "#A16207",
    title: "The OS-style desktop",
    kicker: "Hospital OS behaves like an operating system, not a form farm — windows, dock, command bar.",
    minutes: "1 min",
    steps: [
      { title: "Sign in at the console", desc: "On the demo, the hospital commandant logs in as CMD.ANITA with PIN 2468 — the shell boots like a desktop OS." },
      { title: "Launch modules as windows", desc: "A dock plus command bar open any of 21+ clinical modules as draggable, resizable windows you can arrange freely." },
      { title: "Multitask like a desktop", desc: "Keep the OPD queue beside the EHR, pin labs above billing — window state persists across the session." },
      { title: "Command everything", desc: "⌘K inside the OS opens the palette to jump to patients, modules and actions without touching the mouse." },
      { title: "Your dock matches your role", desc: "RBAC decides what each user sees — a nurse boots into nursing tools, a doctor into clinical ones." },
    ],
    hood: ["Window manager", "Zustand kernel", "Role-aware dock", "Command palette"],
  },
  {
    id: "booking",
    group: "patients",
    icon: CalendarDays,
    accent: "#A16207",
    title: "Book a visit",
    kicker: "From homepage tap to confirmed appointment in four steps — no account needed to start.",
    minutes: "1 min",
    steps: [
      { title: "Open the wizard", desc: "The “Book a visit” button in the top bar opens a calm four-step flow: Specialty → Date → Time → Details." },
      { title: "Pick specialty and day", desc: "Choose from Cardiology, Family Medicine, Endocrinology, Dermatology, Mental Health or Pediatrics, across the next 10 days." },
      { title: "Choose a real slot", desc: "Every slot is validated against the doctor's OPD schedule — double-booking is structurally impossible." },
      { title: "Confirm in one screen", desc: "Name, email and a one-line reason are posted to the scheduling API; a toast confirms instantly." },
      { title: "It appears everywhere at once", desc: "The appointment shows up in Hospital OS's schedule module immediately — front desk, doctor and system all agree." },
    ],
    hood: ["/api/nx/patients", "/api/nx/schedule", "Slot validation", "Toast confirmation"],
    cta: { kind: "booking", label: "Book a visit now" },
  },
  {
    id: "kyh",
    group: "patients",
    icon: Sparkles,
    accent: "#A16207",
    title: "Know Your Health — 15 AI tools",
    kicker: "The free, public wing of the ecosystem. Every tool is live and powered by Gemini — no login required.",
    minutes: "3 min",
    steps: [
      { title: "Analyze — understand your body", desc: "Symptom Checker (plain-language triage), Lab Report Analyzer (photo → values checked against ICMR Indian ranges), Disease Risk Predictor (10-year diabetes / heart / kidney risk), BP Analyzer, Sleep Quality Analyzer and Med Interaction Checker." },
      { title: "Scan — point your camera at it", desc: "Derma Scan reads skin concerns, X-Ray AI Reader gives a chest-film second opinion, and Food & Nutrition Scan turns a photo of your plate into calories and macros." },
      { title: "Manage — live better daily", desc: "AI Diet Planner builds 7-day Indian meal plans, Diabetes Care Coach tracks sugar trends, Women's Care covers cycle / fertility / PCOS, Mental Wellness runs PHQ-9 + GAD-7 with a warm AI reflection." },
      { title: "Learn — know your roots", desc: "Ayurveda Prakriti discovers your dosha constitution in 20 questions, and the Health Quiz gamifies 10 fresh questions on nutrition, hygiene and first aid." },
      { title: "How a call actually works", desc: "Your input goes to /api/nx/ai/* → the governance layer (consent, rate and prompt guards) → Gemini 2.0 Flash (Vision when a photo is involved) → a structured, plain-English answer." },
      { title: "Failure is polite", desc: "If AI is unreachable you get a clear, human message and a retry — never a silent failure or a fake answer." },
    ],
    hood: ["Gemini 2.0 Flash + Vision", "AI governance gates", "ICMR-aligned ranges", "Vision OCR path", "75s client timeouts"],
    cta: { kind: "link", label: "Open Know Your Health", href: "/know-your-health" },
  },
  {
    id: "portal",
    group: "patients",
    icon: HeartPulse,
    accent: "#A16207",
    title: "Patient Portal",
    kicker: "One place for everything the hospital knows about you — plus blood tests from home.",
    minutes: "2 min",
    steps: [
      { title: "Sign in to your own record", desc: "Patient sessions are server-scoped to their own record — a technical impossibility to peek at anyone else's." },
      { title: "Read one timeline, not PDFs", desc: "Visits, prescriptions, lab results and documents stitch into a single chronological health story with inline trends and flags." },
      { title: "Book a blood test at home", desc: "Phlebotomy visits flow through the same scheduling backbone as hospital OPD slots — pick a day, a slot, done." },
      { title: "Reports arrive structured", desc: "Lab values land as data, not scans — so trends render, flags highlight and nothing gets lost between visits." },
      { title: "Stay connected", desc: "From the portal you can jump into Nexura Connect to continue the conversation with your care team." },
    ],
    hood: ["Role-scoped authz", "Structured lab values", "Home collection", "Encounter timeline"],
    cta: { kind: "link", label: "Open Patient Portal", href: "/portal" },
  },
  {
    id: "connect",
    group: "patients",
    icon: MessageCircle,
    accent: "#A16207",
    title: "Nexura Connect",
    kicker: "Chat, voice and video that opens itself at exactly the right moment.",
    minutes: "2 min",
    steps: [
      { title: "Threads create themselves", desc: "When a consultation completes — or the symptom triage flags urgency — a Connect thread opens automatically between patient and care team." },
      { title: "Realtime, tamper-proof chat", desc: "Messages stream over signed SSE: realtime delivery that is authenticated, audit-friendly and immune to forgery." },
      { title: "Escalate to voice or video", desc: "One tap turns a chat into a call; rooms are created per encounter, never per stranger." },
      { title: "Doctors stay in their desktop", desc: "Clinicians answer from the same Hospital OS shell they already work in — no second app, no lost context." },
      { title: "It becomes the record", desc: "Consent-gated threads are stored as part of the medical record — clinical history, not a social feed." },
    ],
    hood: ["Signed SSE", "Encounter-based rooms", "Voice + video", "Clinician-only writes"],
    cta: { kind: "link", label: "Open Connect", href: "/connect" },
  },
  {
    id: "global",
    group: "patients",
    icon: Globe,
    accent: "#A16207",
    title: "Nexura Global",
    kicker: "Medical tourism, done properly — world-class Indian healthcare for international patients.",
    minutes: "2 min",
    steps: [
      { title: "Discover before you fly", desc: "A discovery portal presents hospital profiles, specialties, accreditations and honest cost bands by city." },
      { title: "Estimate the real number", desc: "The cost calculator prices treatment packages across procedures and cities — before any commitment." },
      { title: "A coordinator owns your case", desc: "Every enquiry lands on a coordinator dashboard that tracks the journey from first question to post-op follow-up." },
      { title: "Logistics in one pipeline", desc: "Treatment estimates, medical visa letters, travel and stay are coordinated as one trackable flow." },
      { title: "Same hospital, no parallel universe", desc: "On arrival, international patients enter the very same Hospital OS that local patients use — one standard of care." },
    ],
    hood: ["Cost calculator", "Coordinator dashboard", "Enquiry pipeline", "Hospital profiles"],
    cta: { kind: "link", label: "Open Nexura Global", href: "/global" },
  },
];
