import {
  Stethoscope, FlaskConical, HeartPulse, Flower2, ScanLine, Leaf,
  Brain, ShieldAlert, Activity, Apple, UtensilsCrossed,
  Moon, Droplet, Pill, Sparkles, type LucideIcon,
} from "lucide-react";

export type ToolCategory = "analyze" | "scan" | "manage" | "learn";
export type Tool = {
  id: string; name: string; tagline: string; description: string;
  icon: LucideIcon; category: ToolCategory; accent: string; gradient: string;
  poweredBy: string; inspiration: string; vision?: boolean;
};

export const CATEGORY_LABEL: Record<ToolCategory, string> = {
  analyze: "Analyze", scan: "Scan with AI", manage: "Manage", learn: "Learn",
};

export const TOOLS: Tool[] = [
  { id:"symptoms-checker", name:"Symptom Checker", tagline:"AI triage in plain language", description:"Describe your symptoms — Gemini cross-references against an Indian clinical knowledge base and suggests likely causes, urgency level, and next steps.", icon:Stethoscope, category:"analyze", accent:"#D98B6E", gradient:"linear-gradient(135deg, #D98B6E 0%, #C97A5D 100%)", poweredBy:"Gemini 2.0 Flash", inspiration:"Infermedica · Ada Health" },
  { id:"lab-analyzer", name:"Lab Report Analyzer", tagline:"Upload a blood report — get plain-English meaning", description:"Snap a photo of your lab report — Gemini extracts every value, flags abnormal ones against ICMR Indian ranges, and explains what each means.", icon:FlaskConical, category:"analyze", accent:"#9DB89E", gradient:"linear-gradient(135deg, #9DB89E 0%, #7A9A7B 100%)", poweredBy:"Gemini 2.0 Flash Vision", inspiration:"Tata 1mg · Apollo 24/7", vision:true },
  { id:"disease-risk", name:"Disease Risk Predictor", tagline:"10-year risk for diabetes, heart, kidney", description:"Answer 12 lifestyle questions — Gemini estimates your 10-year risk for Type 2 diabetes, cardiovascular disease, and chronic kidney disease using ICMR-INDIAB risk scores.", icon:ShieldAlert, category:"analyze", accent:"#C98A7A", gradient:"linear-gradient(135deg, #C98A7A 0%, #A96A5A 100%)", poweredBy:"Gemini 2.0 Flash", inspiration:"ASCVD Risk Estimator+ · QDiabetes" },
  { id:"derma-scan", name:"Derma Scan", tagline:"Skin concerns — instant AI read", description:"Upload a close-up of a skin concern — Gemini describes visible features, suggests possible conditions, and rates urgency. Not a diagnosis.", icon:ScanLine, category:"scan", accent:"#E0B080", gradient:"linear-gradient(135deg, #E0B080 0%, #D09A60 100%)", poweredBy:"Gemini 2.0 Flash Vision", inspiration:"SkinVision · FirstDerm", vision:true },
  { id:"xray-reader", name:"X-Ray AI Reader", tagline:"Chest X-ray second opinion", description:"Upload a chest X-ray — Gemini describes visible anatomical findings, notes possible abnormalities, and recommends whether to consult a radiologist.", icon:Activity, category:"scan", accent:"#7A9A7B", gradient:"linear-gradient(135deg, #7A9A7B 0%, #5A7A5B 100%)", poweredBy:"Gemini 2.0 Flash Vision", inspiration:"Qure.ai · Google LYNA", vision:true },
  { id:"food-scan", name:"Food & Nutrition Scan", tagline:"Snap your plate — get the macros", description:"Upload a photo of any meal — Gemini identifies the dish, estimates portion size, and breaks down approximate calories, protein, carbs, fat, and fibre.", icon:Apple, category:"scan", accent:"#9DB89E", gradient:"linear-gradient(135deg, #9DB89E 0%, #B5C9A6 100%)", poweredBy:"Gemini 2.0 Flash Vision", inspiration:"MyFitnessPal · Calorie Mama", vision:true },
  { id:"diet-planner", name:"AI Diet Planner", tagline:"Personalised Indian meal plan in seconds", description:"Tell Gemini your goal, dietary preference, and calorie target — get a 7-day Indian meal plan with recipes, grocery list, and macro breakdown.", icon:UtensilsCrossed, category:"manage", accent:"#D98B6E", gradient:"linear-gradient(135deg, #D98B6E 0%, #E0B080 100%)", poweredBy:"Gemini 2.0 Flash", inspiration:"Eat This Much · Healthify" },
  { id:"diabetes-care", name:"Diabetes Care Coach", tagline:"Your daily T2D companion", description:"Log your fasting/post-meal sugar, HbA1c, meals, and activity — Gemini interprets trends against ICMR-INDIAB targets and suggests adjustments.", icon:HeartPulse, category:"manage", accent:"#C98A7A", gradient:"linear-gradient(135deg, #C98A7A 0%, #D98B6E 100%)", poweredBy:"Gemini 2.0 Flash", inspiration:"BeatO · MySugr" },
  { id:"womens-care", name:"Women's Care", tagline:"Cycle, fertility, pregnancy, PCOS", description:"Track your cycle, log symptoms, or ask fertility/PCOS/pregnancy questions — Gemini responds with warm, evidence-based Indian-context guidance.", icon:Flower2, category:"manage", accent:"#E0B080", gradient:"linear-gradient(135deg, #E0B080 0%, #F0C0A0 100%)", poweredBy:"Gemini 2.0 Flash", inspiration:"Flo · Clue" },
  { id:"ayurveda", name:"Ayurveda Prakriti", tagline:"Discover your dosha constitution", description:"Answer 20 questions about your body, digestion, sleep, and temperament — Gemini determines your Prakriti and suggests diet and dinacharya.", icon:Leaf, category:"learn", accent:"#9DB89E", gradient:"linear-gradient(135deg, #9DB89E 0%, #A8C8A9 100%)", poweredBy:"Gemini 2.0 Flash", inspiration:"NIIMH Ayurveda" },
  { id:"health-quiz", name:"Health Quiz", tagline:"10 questions. How health-smart are you?", description:"A fun, gamified 10-question quiz covering nutrition, hygiene, common diseases, and first aid — adapted for India. Gemini generates fresh questions each session.", icon:Brain, category:"learn", accent:"#D98B6E", gradient:"linear-gradient(135deg, #D98B6E 0%, #F0A090 100%)", poweredBy:"Gemini 2.0 Flash", inspiration:"Khan Academy · Health IQ" },
  { id:"mental-wellness", name:"Mental Wellness Check", tagline:"PHQ-9 + GAD-7 + AI reflection", description:"Take the standard PHQ-9 and GAD-7 screenings, then Gemini adds a warm reflective summary with grounding exercises and crisis-line resources.", icon:Sparkles, category:"manage", accent:"#7A9A7B", gradient:"linear-gradient(135deg, #7A9A7B 0%, #9DB89E 100%)", poweredBy:"Gemini 2.0 Flash", inspiration:"Wysa · Headspace" },
  { id:"bp-analyzer", name:"Blood Pressure Analyzer", tagline:"Understand your BP pattern", description:"Log a week of BP readings — Gemini classifies per ACC/AHA + ICMR guidelines, flags white-coat vs. sustained hypertension.", icon:Droplet, category:"analyze", accent:"#C98A7A", gradient:"linear-gradient(135deg, #C98A7A 0%, #E0B080 100%)", poweredBy:"Gemini 2.0 Flash", inspiration:"Omron Connect · SmartBP" },
  { id:"sleep-quality", name:"Sleep Quality Analyzer", tagline:"Why you wake up tired", description:"Log bedtime, wake time, awakenings, and how you feel — Gemini identifies sleep-pattern issues and suggests Indian-context sleep hygiene fixes.", icon:Moon, category:"analyze", accent:"#5A7A5B", gradient:"linear-gradient(135deg, #5A7A5B 0%, #7A9A7B 100%)", poweredBy:"Gemini 2.0 Flash", inspiration:"Sleep Cycle · Rise" },
  { id:"med-interaction", name:"Med Interaction Checker", tagline:"Will these meds clash?", description:"List your medicines and supplements — Gemini checks for known drug-drug and drug-food interactions, severity, and clinical action.", icon:Pill, category:"analyze", accent:"#E0B080", gradient:"linear-gradient(135deg, #E0B080 0%, #D98B6E 100%)", poweredBy:"Gemini 2.0 Flash", inspiration:"Drugs.com · Medscape" },
];

export const TOOLS_BY_ID = Object.fromEntries(TOOLS.map((t) => [t.id, t]));
